name: Ubuntu CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '.github/ISSUE_TEMPLATE/*.md'
      - 'build_scripts/**'
      - 'cmudict/**'
      - 'colorcurves/**'
      - 'controllers/**'
      - 'documentation/**'
      - 'download/**'
      - 'images/**'
      - 'lib/windows/**'
      - 'lib/windows64/**'
      - 'meshobjects/**'
      - 'palettes/**'
      - 'scripts/**'
      - 'songs/**'
      - 'TipOfDay/**'
      - 'valuecurves/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - '*.docx'
      - 'README.*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '.github/ISSUE_TEMPLATE/*.md'
      - 'build_scripts/**'
      - 'cmudict/**'
      - 'colorcurves/**'
      - 'controllers/**'
      - 'documentation/**'
      - 'download/**'
      - 'images/**'
      - 'meshobjects/**'
      - 'palettes/**'
      - 'scripts/**'
      - 'songs/**'
      - 'TipOfDay/**'
      - 'valuecurves/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - '*.docx'
      - 'README.*'    
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install g++ gcc build-essential libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev freeglut3-dev libavcodec-dev libavformat-dev libswscale-dev libsdl2-dev libswresample-dev libavutil-dev libavresample-dev libportmidi-dev libzstd-dev libcurl4-openssl-dev libltc-dev liblua5.3-dev wget git cbp2make
    - name: Make
      run: make -j 2

